config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  root 'announces#index'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'

  resources :users do
    member do
      get :get_stuhomeworks
      get :get_my_topic
      get :get_my_question
    end
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :announces
  resources :questions do
    resources :answers, only: [:create]
  end
  resources :answers, only: [:edit, :update, :destroy]

  resources :coursewares

  resources :homeworks do
    resources :stuhomeworks, only: [:create]
  end

  resources :stuhomeworks, only: [:edit, :update, :destroy] do
    member do
      get :check
      get :get_stuhomeworks
      patch :check_complete
    end
  end

  resources :notifications, only: [:index, :destroy, :clear]

  resources :stuclasses

  get 'stu_home' => 'users#stu_home'

  mount RuCaptcha::Engine => "/rucaptcha"

  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :topics

  resources :experiments

  namespace :admin do
    root to: 'pages#index', as: 'root'
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :announces, only: [:index, :edit, :update, :destroy]
    resources :coursewares, only: [:index, :edit, :update, :destroy]
    resources :stuclasses do
      member do
        get :remove_student
      end
    end

    resources :topics, only: [:index, :edit, :update, :destroy] do
      member do
        get :show_comments
      end
    end

    resources :questions, only: [:index, :edit, :update, :destroy] do
      resources :answers, only: [:index]
    end
    resources :answers, only: [:edit, :update, :destroy] do
      member do
        get :show_comments
      end
    end

    resources :homeworks, only: [:index, :edit, :update, :destroy] do
      resources :stuhomeworks, only: [:index]
    end
    resources :stuhomeworks, only: [:edit, :update, :destroy]
    resources :comments

    resources :experiments, only: [:index, :edit, :update, :destroy]
  end

end

app/models/stuhomework.rb
class Stuhomework < ApplicationRecord
  belongs_to :user
  belongs_to :homework
  mount_uploader :stuhomeworkfile, StuHomeWorkUploader
  validates :stuhomeworkfile, presence: true
end

app/controllers/admin/stuhomeworks_controller.rb
class Admin::StuhomeworksController < Admin::AdminController
  def index
    @homework = Homework.find params[:homework_id]
    @stuhomeworks = @homework.stuhomeworks.page params[:page]
  end

  def edit
    @stuhomework = Stuhomework.find params[:id]
  end

  def update
    @stuhomework = Stuhomework.find params[:id]
    #binding.pry
    if @stuhomework.update_attributes stuhomework_params
      flash[:success] = '学生作业资料修改成功'
      redirect_to admin_homework_stuhomeworks_url @stuhomework.homework
    else
      render 'edit'
    end
  end

  def destroy
    stuhomework = Stuhomework.find(params[:id])
    file_delete stuhomework.stuhomeworkfile
    stuhomework.destroy
    flash[:success] = '作业删除成功'
    redirect_to admin_homework_stuhomeworks_url stuhomework.homework
  end

  private

  def stuhomework_params
    params.require(:stuhomework).permit(:stuhomeworkfile, :mark, :remark, :ischecked)
  end

end

app/controllers/stuhomeworks_controller.rb
class StuhomeworksController < ApplicationController
  before_action :logged_in_user
  before_action :ischecked, only: [:edit, :update]
  before_action only: [:check, :check_complete] do
    if !teacher_admin?
      flash[:warning] = '权限不够，无法操作'
      redirect_to root_url
    end
  end
  before_action only: [:create] do
    @homework = Homework.find(params[:homework_id])
    notcreated? @homework
  end
  before_action only: [:edit, :update] do
    @stuhomework = Stuhomework.find params[:id]
    correct_user @stuhomework.user
  end

  def index
    @stuhomeworks = Stuhomework.page params[:page]
  end

  def create
    @homework = Homework.find(params[:homework_id])
    @stuhomework = @homework.stuhomeworks.new(stuhomework_params.merge(user_id: current_user.id))
    if @stuhomework.save
      # success
      flash[:success] = '提交作业成功'
      redirect_to @homework
    else
      flash[:warning] = '提交失败'
      redirect_to @homework
    end
  end

  def edit
    @stuhomework = Stuhomework.find(params[:id])
  end

  def update
    @stuhomework = Stuhomework.find(params[:id])
    if @stuhomework.update_attributes(stuhomework_params)
      flash[:success] = '作业修改成功'
      @homework = @stuhomework.homework
      redirect_to @homework
    else
      render 'edit'
    end
  end

  def destroy
    @stuhomework = Stuhomework.find(params[:id])
    @homework = @stuhomework.homework
    @stuhomework.destroy
    flash[:success] = '作业已删除'
    redirect_to @homework
  end

  def check
    @stuhomework = Stuhomework.find(params[:id])
  end

  def check_complete
    @stuhomework = Stuhomework.find(params[:id])
    if @stuhomework.update_attributes(checked_params.merge(ischecked: true))
      flash[:success] = '作业批改成功'
      redirect_to @stuhomework.homework
    else
      render 'check'
    end
  end

  private
  def stuhomework_params
    params.require(:stuhomework).permit(:stuhomeworkfile)
  end

  def checked_params
    params.require(:stuhomework).permit(:mark, :remark)
  end

  def ischecked
    @stuhomework = Stuhomework.find params[:id]
    if @stuhomework.ischecked?
      @homework = @stuhomework.homework
      flash[:danger] = '已经批改过，无法进行修改'
      redirect_to @homework
    end
  end

end

app/helpers/admin/stuhomeworks_helper.rb
module Admin::StuhomeworksHelper
end

app/helpers/stuhomeworks_helper.rb
module StuhomeworksHelper

  def notcreated? homework
    homework.stuhomeworks.where(user_id: current_user.id).blank?
  end

end

app/views/stuhomeworks/_form.html.erb
<% if @homework.stuclasses.include? current_user.stuclass %>
<div class="panel panel-default">
  <div class="panel-heading">提交作业</div>
  <div class="panel-body">
    <%= form_for([@homework, @stuhomework = Stuhomework.new], html: { multipart: true }) do |f| %>
    <%= render "shared/error_messages", object: @stuhomework %>
    <div class="form-group">
      <%= f.file_field :stuhomeworkfile, class: "form-control" %>
    </div>
      <%= f.hidden_field :ischecked %>
    <div class="form-group">
      <%= f.submit "提交作业", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/stuhomeworks/_show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= "已经有#{@homework.stuhomeworks.count} 人次提交作业" %>
  </div>
  <table class="table table-striped">
    <tr>
      <td>用户名</td>
      <td>学号</td>
      <td>班级</td>
      <td>是否批改</td>
      <td>分数</td>
    </tr>
    <% @homework.stuhomeworks.each do |stuhomework| %>
      <tr>
        <td><%= stuhomework.user.name %></td>
        <td><%= stuhomework.user.sid %></td>
        <td>
          <% if stuhomework.user.stuclass_id.present? %>
            <%= Stuclass.find(stuhomework.user.stuclass_id).scname %>
          <% end %>
        </td>
        <td><%= stuhomework.ischecked ? '是' : '否' %></td>
        <td><%= stuhomework.mark %></td>
        <% if teacher_admin? %>
          <td><a href="#{<%= stuhomework.stuhomeworkfile %>}">下载作业</a></td>
          <td><%= link_to '评分', check_stuhomework_path(stuhomework) %></td>
        <% end %>
        <!--用户可以在老师批改之前修改或者删除自己的作业-->
        <% if current_user == stuhomework.user && !stuhomework.ischecked %>
          <td><%= link_to edit_stuhomework_path(stuhomework) do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %> |
          <%= link_to stuhomework_path(stuhomework), method: :delete, data: { confirm: '确定要删除么' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      <% end %>

    </tr>
  <% end %>
</table>
</div>
<% if student? && notcreated?(@homework) %>
  <%= render 'stuhomeworks/form' %>
<% end %>

app/views/stuhomeworks/check.html.erb
<% provide(:title, '批改作业') %>
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">批改作业</div>
      <div class="panel-body">
        <%= form_for @stuhomework, url: check_complete_stuhomework_path do |f| %>
          <%= render "shared/error_messages", object: f.object %>
          <div class="form-group">
            <%= f.text_field :mark, class: "form-control", placeholder: "在这里填写分数" %>
          </div>
          <div class="form-group">
            <%= f.text_area :remark, class: "form-control", rows: 10, placeholder: "在这里填写评语" %>
          </div>
          <div class="form-group">
            <%= f.submit "完成批改", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <%= render 'panel/user_info' %>
  </div>
</div>

app/views/stuhomeworks/edit.html.erb
<% provide(:title, '修改作业') %>
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">修改作业</div>
      <div class="panel-body">
        <%= form_for ([@homework, @stuhomework]) do |f| %>
          <%= render "shared/error_messages", object: f.object %>
          <div class="form-group">
            <%= f.label :stuhomeworkfile, '作业文件' %>
            <%= f.file_field :stuhomeworkfile, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.submit "完成修改", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <%= render 'panel/user_info' %>
  </div>
</div>

app/views/stuhomeworks/index.html.erb
<h1>Stuhomeworks#index</h1>
<p>Find me in app/views/stuhomeworks/index.html.erb</p>

app/views/stuhomeworks/new.html.erb
<h1>Stuhomeworks#new</h1>
<p>Find me in app/views/stuhomeworks/new.html.erb</p>