config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  root 'announces#index'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'

  resources :users do
    member do
      get :get_stuhomeworks
      get :get_my_topic
      get :get_my_question
    end
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :announces
  resources :questions do
    resources :answers, only: [:create]
  end
  resources :answers, only: [:edit, :update, :destroy]

  resources :coursewares

  resources :homeworks do
    resources :stuhomeworks, only: [:create]
  end

  resources :stuhomeworks, only: [:edit, :update, :destroy] do
    member do
      get :check
      get :get_stuhomeworks
      patch :check_complete
    end
  end

  resources :notifications, only: [:index, :destroy, :clear]

  resources :stuclasses

  get 'stu_home' => 'users#stu_home'

  mount RuCaptcha::Engine => "/rucaptcha"

  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :topics

  resources :experiments

  namespace :admin do
    root to: 'pages#index', as: 'root'
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :announces, only: [:index, :edit, :update, :destroy]
    resources :coursewares, only: [:index, :edit, :update, :destroy]
    resources :stuclasses do
      member do
        get :remove_student
      end
    end

    resources :topics, only: [:index, :edit, :update, :destroy] do
      member do
        get :show_comments
      end
    end

    resources :questions, only: [:index, :edit, :update, :destroy] do
      resources :answers, only: [:index]
    end
    resources :answers, only: [:edit, :update, :destroy] do
      member do
        get :show_comments
      end
    end

    resources :homeworks, only: [:index, :edit, :update, :destroy] do
      resources :stuhomeworks, only: [:index]
    end
    resources :stuhomeworks, only: [:edit, :update, :destroy]
    resources :comments

    resources :experiments, only: [:index, :edit, :update, :destroy]
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  # 一个话题可以有多个评论
  has_many :comments, dependent: :destroy

  validates_presence_of :title, :content
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::AdminController
  def index
    @topics = Topic.page params[:page]
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(topic_params)
      flash[:success] = '话题修改成功'
      redirect_to admin_topics_url
    else
      render 'edit'
    end
  end

  def destroy
    Topic.find(params[:id]).destroy
    flash[:success] = '话题删除成功'
    redirect_to admin_topics_url
  end

  def show_comments
    @topic = Topic.find(params[:id])
    @comments = @topic.comments.page params[:page]
    render 'admin/comments/show_comments'
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :content)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    @topic = Topic.find params[:id]
    correct_user @topic.user
  end

  def index
    # 根据分页显示问题
    @topics= Topic.page params[:page]
  end

  def new
    @topic= Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      flash[:success] = '发布话题成功'
      # 向关注者发送通知
      #create_followers_notification @topic
      redirect_to topics_url
    else
      render 'new'
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def destroy
    Topic.find(params[:id]).destroy
    flash[:success] = '话题删除成功'
    redirect_to topics_url
  end

  def edit
    @topic= Topic.find(params[:id])
  end

  def update
    @topic= Topic.find(params[:id])
    if @topic.update_attributes(update_params)
      flash[:success] = '修改话题成功'
      redirect_to @topic
    else
      render 'edit'
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :content)
  end

  def update_params
    params.require(:topic).permit(:title, :content)
  end

end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/views/admin/topics/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    话题修改
  </div>
  <div class="panel-body">
    <%= form_for [:admin, @topic] do |f| %> 
      <%= f.label :title, '标题' %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :content, '内容' %>
      <%= f.text_field :content, class: 'form-control' %>
      <label>发布者</label>
      <input class="form-control" type="text" readonly="value" value="<%= @topic.user.name %>">
      <%= f.submit '保存修改', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/topics/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">话题列表</div>
  <table class="table">
    <tr>
      <td>话题标题</td>
      <td>内容</td>
      <td>发布者</td>
      <td>评论</td>
    </tr>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= sanitize topic.content %></td>
        <td><%= topic.user.name %></td>
        <td><%= link_to '点击查看', show_comments_admin_topic_path(topic) %></td>
        <td><%= render 'admin/panel/edit_delete', obj: topic %></td>
    </tr>
  <% end %>
  <%= paginate @topics %>
</table>
</div>

app/views/admin/topics/show_comments.html.erb
<div class="panel panel-default">
  <div class="panel-heading">评论列表</div>
  <table class="table">
    <tr>
      <td>内容</td>
      <td>发布者</td>
    </tr>
    <% @comments.each do |comments| %>
      <tr>
        <td><%= comments.content %></td>
        <td><%= comments.user.name %></td>
        <td><%= render 'admin/panel/edit_delete', obj: comments %></td>
      </tr>
    <% end %>
  </table>
  <%= paginate @comments %>
</div>