config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  root 'announces#index'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'

  resources :users do
    member do
      get :get_stuhomeworks
      get :get_my_topic
      get :get_my_question
    end
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :announces
  resources :questions do
    resources :answers, only: [:create]
  end
  resources :answers, only: [:edit, :update, :destroy]

  resources :coursewares

  resources :homeworks do
    resources :stuhomeworks, only: [:create]
  end

  resources :stuhomeworks, only: [:edit, :update, :destroy] do
    member do
      get :check
      get :get_stuhomeworks
      patch :check_complete
    end
  end

  resources :notifications, only: [:index, :destroy, :clear]

  resources :stuclasses

  get 'stu_home' => 'users#stu_home'

  mount RuCaptcha::Engine => "/rucaptcha"

  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :topics

  resources :experiments

  namespace :admin do
    root to: 'pages#index', as: 'root'
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :announces, only: [:index, :edit, :update, :destroy]
    resources :coursewares, only: [:index, :edit, :update, :destroy]
    resources :stuclasses do
      member do
        get :remove_student
      end
    end

    resources :topics, only: [:index, :edit, :update, :destroy] do
      member do
        get :show_comments
      end
    end

    resources :questions, only: [:index, :edit, :update, :destroy] do
      resources :answers, only: [:index]
    end
    resources :answers, only: [:edit, :update, :destroy] do
      member do
        get :show_comments
      end
    end

    resources :homeworks, only: [:index, :edit, :update, :destroy] do
      resources :stuhomeworks, only: [:index]
    end
    resources :stuhomeworks, only: [:edit, :update, :destroy]
    resources :comments

    resources :experiments, only: [:index, :edit, :update, :destroy]
  end

end

app/views/layouts/admin/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
<div class="container">
  <%= link_to "花椒网安", admin_root_path, id: "logo"  %>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li>
      <%= link_to root_path do %>
        <span class="glyphicon glyphicon-home">首页</span>
      <% end %>
      </li>
    </ul>
    <nav>
    <ul class="nav navbar-nav pull-right">
      </li>
      <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <%= current_user.name %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to '个人资料', current_user %></li>
        <li><%= link_to '设置', edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li><%= link_to '安全退出', logout_path, method: "delete" %></li>
      </ul>
      </li>
    </ul>
    </nav>
  </div>
  </header>

app/views/layouts/admin/_sidebar.html.erb
<div class="row">
    <ul class="nav nav-list">
      <li><%= link_to '系统用户管理', admin_users_path %></li>
      <li><%= link_to '公告管理', admin_announces_path %></li>
      <li><%= link_to '课件管理', admin_coursewares_path %></li>
      <li><%= link_to '实验管理', admin_experiments_path %></li>
      <li><%= link_to '作业管理', admin_homeworks_path %></li>
      <li><%= link_to '班级管理', admin_stuclasses_path %></li>
      <li><%= link_to '话题管理', admin_topics_path %></li>
      <li><%= link_to '问答管理', admin_questions_path %></li>
    </ul>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <!---引用application.css-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <!--引用application.js-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!--避免跨站请求(CSRF)伪造攻击-->
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script> <![endif]-->
  </head>
  <body>
    <%= render 'layouts/admin/header' %>

    <div class="container">
      <div class="col-md-3">
        <%= render 'layouts/admin/sidebar' %>
      </div>
      <div class="col-md-9">
        <!---布局中添加闪现的消息-->
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>