config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  root 'announces#index'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'

  resources :users do
    member do
      get :get_stuhomeworks
      get :get_my_topic
      get :get_my_question
    end
  end
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :announces
  resources :questions do
    resources :answers, only: [:create]
  end
  resources :answers, only: [:edit, :update, :destroy]

  resources :coursewares

  resources :homeworks do
    resources :stuhomeworks, only: [:create]
  end

  resources :stuhomeworks, only: [:edit, :update, :destroy] do
    member do
      get :check
      get :get_stuhomeworks
      patch :check_complete
    end
  end

  resources :notifications, only: [:index, :destroy, :clear]

  resources :stuclasses

  get 'stu_home' => 'users#stu_home'

  mount RuCaptcha::Engine => "/rucaptcha"

  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :topics

  resources :experiments

  namespace :admin do
    root to: 'pages#index', as: 'root'
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :announces, only: [:index, :edit, :update, :destroy]
    resources :coursewares, only: [:index, :edit, :update, :destroy]
    resources :stuclasses do
      member do
        get :remove_student
      end
    end

    resources :topics, only: [:index, :edit, :update, :destroy] do
      member do
        get :show_comments
      end
    end

    resources :questions, only: [:index, :edit, :update, :destroy] do
      resources :answers, only: [:index]
    end
    resources :answers, only: [:edit, :update, :destroy] do
      member do
        get :show_comments
      end
    end

    resources :homeworks, only: [:index, :edit, :update, :destroy] do
      resources :stuhomeworks, only: [:index]
    end
    resources :stuhomeworks, only: [:edit, :update, :destroy]
    resources :comments

    resources :experiments, only: [:index, :edit, :update, :destroy]
  end

end

app/models/announce.rb
class Announce < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/admin/announces_controller.rb
class Admin::AnnouncesController < Admin::AdminController
  def index
    @announces = Announce.page params[:page]
  end

  def edit
    @announce = Announce.find(params[:id])
  end

  def update
    @announce = Announce.find(params[:id])
    if @announce.update_attributes(announce_params)
      flash[:success] = '公告修改成功'
      redirect_to admin_announces_url
    else
      render 'edit'
    end
  end

  def destroy
    Announce.find(params[:id]).destroy
    flash[:success] = '公告删除成功'
    redirect_to admin_announces_url
  end

  private
  def announce_params
    params.require(:announce).permit(:title, :content)
  end
end

app/controllers/announces_controller.rb
class AnnouncesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :new, :edit, :update, :show]
  before_action :teacher_admin_user, only: [:new, :create, :destroy, :edit, :update]
  before_action only: [:edit, :update, :destroy] do
    @announce = Announce.find params[:id]
    correct_user @announce.user
  end

  def index
    @announces = Announce.page params[:page]
  end

  def new
    @announce = Announce.new
  end

  def create
    @announce = current_user.announces.new(announce_params)
    if @announce.save
      flash[:success] = '发布公告成功！'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    Announce.find(params[:id]).destroy
    flash[:success] = '公告删除成功！'
    redirect_to announces_url
  end

  def show
    @announce = Announce.find(params[:id])
  end

  def edit
    @announce = Announce.find(params[:id])
  end

  def update
    @announce = Announce.find(params[:id])
    if @announce.update_attributes(announce_params)
      flash[:success] = '公告修改成功！'
      redirect_to @announce
    else
      render 'edit'
    end
  end

  private

  def announce_params
    params.require(:announce).permit(:title, :content)
  end
end

app/helpers/admin/announces_helper.rb
module Admin::AnnouncesHelper
end

app/views/announces/_edit_delete.html.erb
<% if current_user == @announce.user %>
  <%= link_to edit_announce_path(@announce) do %>
    <span class="glyphicon glyphicon-pencil"></span>
  <% end %> |
  <%= link_to @announce, method: :delete, data: { confirm: '确定要删除么' } do %>
    <span class="glyphicon glyphicon-trash"></span>
  <% end %>
<% end %>

app/views/announces/edit.html.erb
<% provide(:title, '公告修改') %>

<div class="row">
  <div class="col-md-9">
    <h2>公告修改</h2>
    <%= form_for(@announce) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :title, '公告标题' %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :content, '公告内容' %>
    <%= f.text_area :content, class: 'form-control', id: 'sim-editor' %>
    <%= f.submit "保存修改", class: "btn btn-primary" %>
    <% end %>

  </div>
  <div class="col-md-3">
    <%= render 'panel/user_info' %>
  </div>
</div>
<%= render 'layouts/simditor' %>

app/views/announces/index.html.erb
<% provide(:title, "首页") %>
<% if logged_in? %>
  <div class="row">
    <div class="col-md-9">
      <%= render 'panel/item_list', contents: @announces, title: '公告列表' %>
      <% if Courseware.all.where(isvideo: true).present? %>
        <div class="panel panel-default">
          <div class="panel-heading">最新视频</div>
          <div class="panel-body">
            <video width="800" src=<%= "#{Courseware.all.where(isvideo: true).last.coursefile}" %> controls="controls"></video>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-3">
      <%= render 'panel/user_info' %>
      <% if teacher_admin? %>
        <%= render 'panel/new_item', content: 'announce', title: '新建公告' %>
      <% end %>
      <%= render 'panel/study_resources' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>欢迎来到花椒网安</h1>
    <p>花椒网安--志在为花椒网络安全技术课程服务</p>
    <%= link_to '现在注册', signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/announces/new.html.erb
<%= provide(:title, '发布公告') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        新建公告
      </div>
      <div class="panel-body">
        <%= form_for(@announce) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :title, '标题' %>
        <%= f.text_field :title, placeholder: "输入标题", class: "form-control" %>
        <%= f.label :content, '公告内容' %>
        <%= f.text_area :content, class: "form-control", placeholder: '说点什么...', id: "sim-editor" %>
        <%= f.submit "发布", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/simditor' %>

app/views/announces/show.html.erb
<% provide(:title, @announce.title) %>
<div class="row">
  <div class="col-md-9">

    <div class="panel panel-default">


      <%= render 'panel/author_panel', content: @announce %>

      <div class="panel-body">
        <p><%= sanitize @announce.content %></p>
      </div>

      <div class="panel-footer">
        <div class="row">
          <div class="col-md-12 text-right">
            <%= render 'edit_delete' %>
          </div>
        </div>
      </div>

    </div>

  </div>
  <div class="col-md-3">
    <%= render 'panel/user_info' %>
    <%= render 'panel/study_resources' %>
  </div>
</div>